### ISSUE TITLE
Setup from scratch ?

### ISSUE THREAD

**Issue by yunusnode** [pancakeswap/pancake-toolkit#105]
Hi,

I want to set up a farm site using the pancakeswap infrastructure, but I don't know where to start. I'll be glad, if you help me ?

**Comment by gbambino** [comment]
Hey, I'm responding to this because I've been trying to figure out how to change the new uikit for 18 hours and finally got it. Hopefully I can save you some time. This is my uikit. I've changed the logos to accept png files. Open src/widgets/menu/icons. Edit each icon path to your preferences.

https://github.com/gbambino/pancake-toolkit.git 

Next, once inside of your changed uikit, run :
"yarn install"
"yarn run build

This will generate a "dist" folder inside of your uikit. Copy this to your clipboard. 
Next, go to your front end file -> /pancake-frontend/node_modules/@pancakeswap/uikit. Replace the "dist" folder with your newly compiled.
Do the same in /pancake-frontend/node_modules/@pancakeswap-libs/uikit

Then inside of your frontend folder,
"yarn install"
"yarn run build"

Now, add the images you pathed to in your uikit. I added a new folder under "public" on the front end. 

I'm a beginner so I'm not sure if all of these steps are necessary, but this is the only way I could get any of the logos to change. When you want to change the uikit, go back into the toolkit folder/uikit, make your changes then run "yarn run build" again. Once again copy paste the "dist" folder in the node_modules of pancake-frontend in @pancakeswap/uikit and @pancakeswap-libs/uikit. 

That's it! To test to make sure it worked, inside of the frontend folder run
"yarn global add serve"
"serve -s build"

Hopefully it works for you too.

**Comment by monomadic** [comment]
The above might work, but it's not the correct way.
https://classic.yarnpkg.com/en/docs/workspaces/

**Comment by monomadic** [comment]
Every time I approach this project, there's always hours and hours of pain because of the terrible solutions npm has for linking local modules. This project is no exception. The above solution is not how you're supposed to do it, it should be as simple as:

# check out the toolkit project
cd packages/pancake-uikit
yarn link

# go back to your main project
yarn add @pancakeswap/uikit

Unfortunately the project at the moment is completely broken.

**Comment by RabbitDoge** [comment]
Use npm / yarn link for local testing.
The project provides a storyboard setup to check your components as well.
